#!/bin/bash
# Script to run ISC Bootstrap Pipeline with FWE Correction and TFCE
# Generated by Agent

TI_CODE="/Users/tongshan/Documents/TemporalIntegration/code/TI_code"
RESULT_DIR="/Users/tongshan/Documents/TemporalIntegration/result/ISC/ISC_bootstrap"
N_PERMS=1000

# Create Output Directories
mkdir -p "$RESULT_DIR/fwe/loo"
mkdir -p "$RESULT_DIR/fwe/pairwise"
mkdir -p "$RESULT_DIR/tfce/loo"
mkdir -p "$RESULT_DIR/tfce/pairwise"

cd "$TI_CODE"

echo "=== Starting ISC Analysis (FWE & TFCE) ==="
echo "Output Directory: $RESULT_DIR"

# ==========================================
# 1. FWE Correction (Max-Statistic)
# ==========================================
echo "--- Running FWE Correction (Max-Statistic) ---"

# LOO
echo "  [FWE] LOO Method..."
python isc/run_isc_pipeline.py --condition TI1_orig --isc_method loo --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method max_stat --output_dir "$RESULT_DIR/fwe/loo"
python isc/run_isc_pipeline.py --condition TI1_sent --isc_method loo --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method max_stat --output_dir "$RESULT_DIR/fwe/loo"
python isc/run_isc_pipeline.py --condition TI1_word --isc_method loo --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method max_stat --output_dir "$RESULT_DIR/fwe/loo"

# Pairwise
echo "  [FWE] Pairwise Method..."
python isc/run_isc_pipeline.py --condition TI1_orig --isc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method max_stat --output_dir "$RESULT_DIR/fwe/pairwise"
python isc/run_isc_pipeline.py --condition TI1_sent --isc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method max_stat --output_dir "$RESULT_DIR/fwe/pairwise"
python isc/run_isc_pipeline.py --condition TI1_word --isc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method max_stat --output_dir "$RESULT_DIR/fwe/pairwise"


# ==========================================
# 2. TFCE Correction
# ==========================================
echo "--- Running TFCE Correction ---"

# LOO
echo "  [TFCE] LOO Method..."
python isc/run_isc_pipeline.py --condition TI1_orig --isc_method loo --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --use_tfce --output_dir "$RESULT_DIR/tfce/loo"
python isc/run_isc_pipeline.py --condition TI1_sent --isc_method loo --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --use_tfce --output_dir "$RESULT_DIR/tfce/loo"
python isc/run_isc_pipeline.py --condition TI1_word --isc_method loo --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --use_tfce --output_dir "$RESULT_DIR/tfce/loo"

# Pairwise
echo "  [TFCE] Pairwise Method..."
python isc/run_isc_pipeline.py --condition TI1_orig --isc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --use_tfce --output_dir "$RESULT_DIR/tfce/pairwise"
python isc/run_isc_pipeline.py --condition TI1_sent --isc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --use_tfce --output_dir "$RESULT_DIR/tfce/pairwise"
python isc/run_isc_pipeline.py --condition TI1_word --isc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --use_tfce --output_dir "$RESULT_DIR/tfce/pairwise"


# ==========================================
# 3. Post-processing (Rethresholding)
# ==========================================
echo "=== Analysis Complete. Starting Re-thresholding ==="

# We can re-threshold the FWE results (as they have p-value maps).
# TFCE results are implicit, but they also generate p-value maps now.

python shared/rethreshold_results.py --result_dir "$RESULT_DIR/fwe" --thresholds 0.01 0.005 0.001 --overwrite
python shared/rethreshold_results.py --result_dir "$RESULT_DIR/tfce" --thresholds 0.01 0.005 0.001 --overwrite

echo "Done."
