#!/bin/bash
# Script to run ISFC Bootstrap TFCE Pipeline for TI project locally
# Generated by Agent

# Directories
TI_CODE="/Users/tongshan/Documents/TemporalIntegration/code/TI_code"
RESULT_DIR="/Users/tongshan/Documents/TemporalIntegration/result/ISFC/bootstrap"

# Create Output Directories
mkdir -p "$RESULT_DIR/tfce/loo"
mkdir -p "$RESULT_DIR/tfce/pairwise"

cd "$TI_CODE"

echo "=== Starting ISFC Analysis (Bootstrap & TFCE) ==="
echo "Pipeline started at: $(date)"

N_PERMS=1000
P_THRESH=0.05

# --- LOO Method ---
echo "Running LOO Method..."

# PMC
python isfc/run_isfc_pipeline.py --condition TI1_orig --isfc_method loo --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 0 --seed_y -53 --seed_z 2 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/loo"
python isfc/run_isfc_pipeline.py --condition TI1_sent --isfc_method loo --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 0 --seed_y -53 --seed_z 2 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/loo"
python isfc/run_isfc_pipeline.py --condition TI1_word --isfc_method loo --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 0 --seed_y -53 --seed_z 2 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/loo"

# LpSTS
python isfc/run_isfc_pipeline.py --condition TI1_orig --isfc_method loo --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x -63 --seed_y -42 --seed_z 9 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/loo"
python isfc/run_isfc_pipeline.py --condition TI1_sent --isfc_method loo --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x -63 --seed_y -42 --seed_z 9 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/loo"
python isfc/run_isfc_pipeline.py --condition TI1_word --isfc_method loo --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x -63 --seed_y -42 --seed_z 9 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/loo"

# RpSTS
python isfc/run_isfc_pipeline.py --condition TI1_orig --isfc_method loo --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 57 --seed_y -31 --seed_z 5 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/loo"
python isfc/run_isfc_pipeline.py --condition TI1_sent --isfc_method loo --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 57 --seed_y -31 --seed_z 5 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/loo"
python isfc/run_isfc_pipeline.py --condition TI1_word --isfc_method loo --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 57 --seed_y -31 --seed_z 5 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/loo"

# --- Pairwise Method ---
echo "Running Pairwise Method..."

# PMC
python isfc/run_isfc_pipeline.py --condition TI1_orig --isfc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 0 --seed_y -53 --seed_z 2 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/pairwise"
python isfc/run_isfc_pipeline.py --condition TI1_sent --isfc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 0 --seed_y -53 --seed_z 2 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/pairwise"
python isfc/run_isfc_pipeline.py --condition TI1_word --isfc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 0 --seed_y -53 --seed_z 2 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/pairwise"

# LpSTS
python isfc/run_isfc_pipeline.py --condition TI1_orig --isfc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x -63 --seed_y -42 --seed_z 9 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/pairwise"
python isfc/run_isfc_pipeline.py --condition TI1_sent --isfc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x -63 --seed_y -42 --seed_z 9 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/pairwise"
python isfc/run_isfc_pipeline.py --condition TI1_word --isfc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x -63 --seed_y -42 --seed_z 9 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/pairwise"

# RpSTS
python isfc/run_isfc_pipeline.py --condition TI1_orig --isfc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 57 --seed_y -31 --seed_z 5 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/pairwise"
python isfc/run_isfc_pipeline.py --condition TI1_sent --isfc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 57 --seed_y -31 --seed_z 5 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/pairwise"
python isfc/run_isfc_pipeline.py --condition TI1_word --isfc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --use_tfce --tfce_dh 0.01 --seed_x 57 --seed_y -31 --seed_z 5 --p_threshold $P_THRESH --output_dir "$RESULT_DIR/tfce/pairwise"

echo "=== Analysis Complete. Starting Re-thresholding ==="

python shared/rethreshold_results.py --result_dir "$RESULT_DIR/tfce" --thresholds 0.01 0.005 0.001 --overwrite

echo "Done."
