#!/bin/bash
# Script to re-run ISC Bootstrap Pipeline with updated subject lists
# Generated by Agent

TI_CODE="/Users/tongshan/Documents/TemporalIntegration/code/TI_code"
# Using the bootstrap results directory confirmed by user
RESULT_DIR="/Users/tongshan/Documents/TemporalIntegration/result/ISC/ISC_bootstrap"

# Create Output Directories (ensure they exist)
mkdir -p "$RESULT_DIR/loo"
mkdir -p "$RESULT_DIR/pairwise"

cd "$TI_CODE"

echo "=== Starting ISC Analysis Re-run (Bootstrap) ==="
echo "Output Directory: $RESULT_DIR"

# --- LOO Method ---
echo "Running LOO Method..."
python isc/run_isc_pipeline.py --condition TI1_orig --isc_method loo --stats_method bootstrap --n_perms 1000 --p_threshold 0.05 --output_dir "$RESULT_DIR/loo"
python isc/run_isc_pipeline.py --condition TI1_sent --isc_method loo --stats_method bootstrap --n_perms 1000 --p_threshold 0.05 --output_dir "$RESULT_DIR/loo"
python isc/run_isc_pipeline.py --condition TI1_word --isc_method loo --stats_method bootstrap --n_perms 1000 --p_threshold 0.05 --output_dir "$RESULT_DIR/loo"

# --- Pairwise Method ---
echo "Running Pairwise Method..."
python isc/run_isc_pipeline.py --condition TI1_orig --isc_method pairwise --stats_method bootstrap --n_perms 1000 --p_threshold 0.05 --output_dir "$RESULT_DIR/pairwise"
python isc/run_isc_pipeline.py --condition TI1_sent --isc_method pairwise --stats_method bootstrap --n_perms 1000 --p_threshold 0.05 --output_dir "$RESULT_DIR/pairwise"
python isc/run_isc_pipeline.py --condition TI1_word --isc_method pairwise --stats_method bootstrap --n_perms 1000 --p_threshold 0.05 --output_dir "$RESULT_DIR/pairwise"

echo "=== Analysis Complete. Starting Re-thresholding ==="

python shared/rethreshold_results.py --result_dir "$RESULT_DIR" --thresholds 0.01 0.005 0.001 --overwrite

echo "Done."
