#!/bin/bash
# Script to run ISC Bootstrap Pipeline with FDR Correction
# Generated by Agent

TI_CODE="/Users/tongshan/Documents/TemporalIntegration/code/TI_code"
RESULT_DIR="/Users/tongshan/Documents/TemporalIntegration/result/ISC/ISC_bootstrap/fdr"
N_PERMS=1000

# Create Output Directories
mkdir -p "$RESULT_DIR/loo"
mkdir -p "$RESULT_DIR/pairwise"

cd "$TI_CODE"

echo "=== Starting ISC Analysis (FDR Correction) ==="
echo "Output Directory: $RESULT_DIR"

# ==========================================
# 1. FDR Correction
# ==========================================

# LOO
echo "  [FDR] LOO Method..."
python isc/run_isc_pipeline.py --condition TI1_orig --isc_method loo --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method fdr --output_dir "$RESULT_DIR/loo"
python isc/run_isc_pipeline.py --condition TI1_sent --isc_method loo --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method fdr --output_dir "$RESULT_DIR/loo"
python isc/run_isc_pipeline.py --condition TI1_word --isc_method loo --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method fdr --output_dir "$RESULT_DIR/loo"

# Pairwise
echo "  [FDR] Pairwise Method..."
python isc/run_isc_pipeline.py --condition TI1_orig --isc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method fdr --output_dir "$RESULT_DIR/pairwise"
python isc/run_isc_pipeline.py --condition TI1_sent --isc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method fdr --output_dir "$RESULT_DIR/pairwise"
python isc/run_isc_pipeline.py --condition TI1_word --isc_method pairwise --stats_method bootstrap --n_perms $N_PERMS --p_threshold 0.05 --fwe_method fdr --output_dir "$RESULT_DIR/pairwise"


echo "=== Analysis Complete. Starting Re-thresholding ==="

# Re-thresholding to see different q-value cutoffs (e.g. 0.01, 0.05)
# Note: The output _desc-pvalues.nii.gz contains FDR q-values.
python shared/rethreshold_results.py --result_dir "$RESULT_DIR" --thresholds 0.05 0.01 0.005 0.001 --overwrite

echo "Done."
